# Generated by Django 4.2.2 on 2026-01-04 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(choices=[('user', 'Human User'), ('system', 'System Process'), ('integration', 'External Integration'), ('bot', 'Automation Bot'), ('scheduled', 'Scheduled Job')], max_length=32)),
                ('identifier', models.CharField(max_length=128)),
                ('display_name', models.CharField(max_length=128)),
                ('roles', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='core.actor')),
            ],
        ),
        migrations.CreateModel(
            name='EntityDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('display_name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('version', models.IntegerField(default=1)),
                ('schema_json', models.JSONField()),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('workflow_template', models.CharField(blank=True, max_length=128, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_definitions', to='core.actor')),
            ],
        ),
        migrations.CreateModel(
            name='EntityInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('data_json', models.JSONField()),
                ('state', models.CharField(default='Draft', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_instances', to='core.actor')),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='core.entitydefinition')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenant_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='core.actor')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(blank=True, max_length=128, null=True)),
                ('model_version', models.CharField(blank=True, max_length=32, null=True)),
                ('entity', models.CharField(blank=True, max_length=128, null=True)),
                ('workflow_name', models.CharField(max_length=128)),
                ('instance_id', models.CharField(max_length=64, unique=True)),
                ('state', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roles', models.JSONField(default=list)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to='core.actor')),
                ('entity_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='core.entityinstance')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tenant', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TenantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=128)),
                ('version', models.CharField(default='draft', max_length=32)),
                ('status', models.CharField(default='draft', max_length=16)),
                ('json_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_models', to='core.actor')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='core.tenant')),
            ],
            options={
                'unique_together': {('tenant_id', 'model_id', 'version')},
            },
        ),
        migrations.CreateModel(
            name='EntityRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_id', models.CharField(blank=True, max_length=128, null=True)),
                ('relationship_type', models.CharField(blank=True, max_length=64, null=True)),
                ('cardinality', models.CharField(blank=True, max_length=64, null=True)),
                ('key_mapping', models.JSONField(default=dict)),
                ('from_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='core.entitydefinition')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='core.tenant')),
                ('to_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='core.entitydefinition')),
            ],
        ),
        migrations.AddField(
            model_name='entityinstance',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_instances', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='entitydefinition',
            name='tenant_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_definitions', to='core.tenantmodel'),
        ),
        migrations.CreateModel(
            name='TransitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(max_length=128)),
                ('to_state', models.CharField(max_length=128)),
                ('event', models.CharField(max_length=128)),
                ('guard_passed', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions', to='core.actor')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.workflowinstance')),
            ],
            options={
                'indexes': [models.Index(fields=['instance', 'created_at'], name='core_transi_instanc_b4d484_idx'), models.Index(fields=['event'], name='core_transi_event_c92962_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Tenant Admin'), ('developer', 'Developer'), ('runtime', 'Runtime User'), ('auditor', 'Auditor (Read-only)'), ('support', 'Support Operator')], max_length=32)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.CharField(blank=True, max_length=128, null=True)),
                ('tenant_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.tenantuser')),
            ],
            options={
                'unique_together': {('tenant_user', 'role')},
            },
        ),
        migrations.AddIndex(
            model_name='entityinstance',
            index=models.Index(fields=['tenant_id', 'entity_type'], name='core_entity_tenant__29fef3_idx'),
        ),
        migrations.AddIndex(
            model_name='entityinstance',
            index=models.Index(fields=['state'], name='core_entity_state_35fe14_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entitydefinition',
            unique_together={('tenant_model', 'name', 'version')},
        ),
    ]
