# Generated by Django 4.2.2 on 2026-01-10 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='entityinstance',
            name='core_entity_tenant__29fef3_idx',
        ),
        migrations.RemoveField(
            model_name='entityinstance',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='entityrelationship',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='workflowinstance',
            name='model_id',
        ),
        migrations.RemoveField(
            model_name='workflowinstance',
            name='tenant',
        ),
        migrations.AddField(
            model_name='entityinstance',
            name='tenant_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_instances', to='core.tenantmodel'),
        ),
        migrations.AddField(
            model_name='entityrelationship',
            name='tenant_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='core.tenantmodel'),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='tenant_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='core.tenantmodel'),
        ),
        migrations.AddIndex(
            model_name='entityinstance',
            index=models.Index(fields=['tenant_model', 'entity_type'], name='core_entity_tenant__2f3013_idx'),
        ),
    ]
