# Generated by Django 4.2.2 on 2026-01-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_entityinstance_core_entity_tenant__29fef3_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitydefinition',
            name='version',
            field=models.CharField(default='draft', max_length=32),
        ),
    ]
