# Generated by Django 4.2.2 on 2026-01-10 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_entitydefinition_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowinstance',
            name='actor',
        ),
    ]
