# Generated by Django 4.2.2 on 2026-01-10 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_workflowinstance_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowinstance',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to='core.actor'),
        ),
    ]
