# Generated by Django 4.2.2 on 2026-01-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_workflowinstance_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitionlog',
            name='actor_roles',
            field=models.JSONField(default=list),
        ),
    ]
