# Generated by Django 4.2.2 on 2026-01-11 21:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_transitionlog_actor_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entityinstance',
            name='data_json',
        ),
        migrations.AddField(
            model_name='entityinstance',
            name='created_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entityinstance',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='entityinstance',
            name='updated_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='created_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='updated_by',
            field=models.CharField(max_length=200, null=True),
        ),        
    ]
