# Generated by Django 4.2.2 on 2026-01-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_entityinstance_data_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityinstance',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
