# Generated by Django 4.2.2 on 2026-01-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_entityinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityinstance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
