# Generated by Django 4.2.2 on 2026-01-11 21:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_entityinstance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityinstance',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='entityinstance',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
