# Generated by Django 4.2.2 on 2026-01-11 21:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_entityinstance_public_id_alter_entityinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityinstance',
            name='public_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
