# Generated by Django 4.2.2 on 2026-01-11 21:20

from django.db import migrations
import uuid


def populate_public_ids(apps, schema_editor):
    EntityInstance = apps.get_model("core", "EntityInstance")
    for row in EntityInstance.objects.all():
        row.public_id = uuid.uuid4()
        row.save(update_fields=["public_id"])




class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_entityinstance_public_id'),
    ]

    operations = [
    migrations.RunPython(populate_public_ids),
]
