# Generated by Django 4.2.2 on 2026-01-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20260111_2120'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='entityinstance',
            new_name='core_entity_tenant__ed40eb_idx',
            old_name='core_entity_tenant__2f3013_idx',
        ),
        migrations.AlterField(
            model_name='entityinstance',
            name='entity_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
