# Generated by Django 4.2.2 on 2026-01-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_core_entity_tenant__2f3013_idx_core_entity_tenant__ed40eb_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityinstance',
            name='version',
            field=models.IntegerField(null=True),
        ),
    ]
