# Generated by Django 4.2.2 on 2026-01-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_entityinstance_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitydefinition',
            name='created_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entitydefinition',
            name='updated_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tenantmodel',
            name='created_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tenantmodel',
            name='updated_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transitionlog',
            name='created_by',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
