# Generated by Django 4.2.2 on 2026-01-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_entitydefinition_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityinstance',
            name='state',
            field=models.CharField(default='Draftss', max_length=64),
        ),
    ]
