# Generated by Django 4.2.2 on 2026-01-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_entityinstance_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityinstance',
            name='state',
            field=models.CharField(default='Draft', max_length=64),
        ),
    ]
